# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: building
    steps:
    - bash: echo ALLAH
- stage: qa
  dependsOn: build
  jobs:
  - job: stage
    steps:
    - bash: echo Mohammed
- stage: prod
  dependsOn: 
  - build   
  - qa
  jobs:
    - job: qa
      steps:
      - bash: echo Ayesha